spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By,Auth Service

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By,Movie Service
  application:
    name: api-gateway

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
